const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const canvas=$('#postCanvas'),ctx=canvas.getContext('2d');
const galleryCanvas=$('#galleryCanvas'),gctx=galleryCanvas.getContext('2d');
const adminCanvas=$('#adminThemePreview'),actx=adminCanvas.getContext('2d');
const W=1080,H=1350;
const DEFAULT_ZONES={photo:{x:710,y:145,w:280,h:280},headline:{x:78,y:260,w:650,h:310},body:{x:78,y:660,w:880,h:355},date:{x:78,y:1160,w:520,h:42},instagram:{x:78,y:1205,w:520,h:42}};
const DEFAULT_TEXT_STYLES={headline:{colorMode:'auto',color:'#111111',shadowEnabled:true,shadowColor:'#000000',shadowBlur:8,shadowOffsetY:2},body:{colorMode:'auto',color:'#111111',shadowEnabled:true,shadowColor:'#000000',shadowBlur:8,shadowOffsetY:2},date:{colorMode:'auto',color:'#111111',shadowEnabled:true,shadowColor:'#000000',shadowBlur:6,shadowOffsetY:2},instagram:{colorMode:'auto',color:'#111111',shadowEnabled:true,shadowColor:'#000000',shadowBlur:6,shadowOffsetY:2}};
let bgImage=null,photoImages=[],activeTheme={name:'Standard',zones:structuredClone(DEFAULT_ZONES),textStyles:structuredClone(DEFAULT_TEXT_STYLES)},adminAuth=null,currentTab='pending';
let textOverflow=false,currentIdempotency=crypto.randomUUID();
let adminConfig=null,adminPreviewImages={standard:null,special:null},adminZones={standard:structuredClone(DEFAULT_ZONES),special:structuredClone(DEFAULT_ZONES)},adminTextStyles={standard:structuredClone(DEFAULT_TEXT_STYLES),special:structuredClone(DEFAULT_TEXT_STYLES)};

function authHeaders(){return adminAuth?{'X-Admin-User':adminAuth.user,'X-Admin-Pass':adminAuth.pass}:{}}
function setStatus(el,msg,ok=true){if(!el)return;el.textContent=msg;el.style.color=ok?'#4b5563':'#b91c1c'}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();if(/^https?:\/\//i.test(src))i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function fileToImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=async()=>{try{res(await loadImage(r.result))}catch(e){rej(e)}};r.onerror=rej;r.readAsDataURL(file)})}
function roundedRectOn(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function drawCoverOn(c,img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),sw=w/s,sh=h/s,sx=(img.width-sw)/2,sy=(img.height-sh)/2;c.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
function cloneZones(z){return structuredClone(z||DEFAULT_ZONES)}
function cloneTextStyles(v){const out=structuredClone(DEFAULT_TEXT_STYLES);for(const k of Object.keys(out)){if(v?.[k])out[k]={...out[k],...v[k]}}return out}
function textStyleFor(key){return {...DEFAULT_TEXT_STYLES[key],...(activeTheme?.textStyles?.[key]||{})}}
function resolveTextStyle(c,b,key){const a=analyzeRegion(c,b),s=textStyleFor(key),color=s.colorMode==='custom'?s.color:a.color;return{...s,color,needsAssist:a.needsAssist}}
function applyShadow(c,s){if(s?.shadowEnabled){c.shadowColor=s.shadowColor||'#000000';c.shadowBlur=Number(s.shadowBlur)||0;c.shadowOffsetX=0;c.shadowOffsetY=Number(s.shadowOffsetY)||0}else{c.shadowColor='transparent';c.shadowBlur=0;c.shadowOffsetX=0;c.shadowOffsetY=0}}
function clampZone(z){return{x:Math.max(0,Math.min(W-20,+z.x||0)),y:Math.max(0,Math.min(H-20,+z.y||0)),w:Math.max(20,Math.min(W-(+z.x||0),+z.w||20)),h:Math.max(20,Math.min(H-(+z.y||0),+z.h||20))}}
function zones(){const z=activeTheme?.zones||DEFAULT_ZONES;return Object.fromEntries(Object.entries(DEFAULT_ZONES).map(([k,v])=>[k,clampZone(z[k]||v)]))}
function wrapTextOn(c,text,maxW){const chars=Array.from((text||'').trim());const lines=[];let line='';for(const ch of chars){if(ch==='\n'){if(line.trim())lines.push(line.trim());line='';continue}const test=line+ch;if(c.measureText(test).width>maxW&&line){lines.push(line.trim());line=ch}else line=test}if(line.trim())lines.push(line.trim());return lines}
function fitText(c,text,box,{maxSize,minSize,weight,lineHeight,maxLines}){let size=maxSize,lines=[];let fits=false;while(size>=minSize){c.font=`${weight} ${size}px Tahoma, "Segoe UI", sans-serif`;lines=wrapTextOn(c,text,box.w);fits=lines.length*size*lineHeight<=box.h&&lines.length<=maxLines;if(fits)break;size-=2}return{size:Math.max(size,minSize),lines,fits}}
function drawFallbackOn(c){const g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'#111827');g.addColorStop(1,'#374151');c.fillStyle=g;c.fillRect(0,0,W,H)}
function drawThemeOn(c){if(bgImage)drawCoverOn(c,bgImage,0,0,W,H);else drawFallbackOn(c)}
function drawBadge(c,x=78,y=70){c.font='900 31px Tahoma, "Segoe UI", sans-serif';const tag='#ฝากบอกพิริ',tagW=c.measureText(tag).width+42;c.fillStyle='#fff';roundedRectOn(c,x,y,tagW,58,18);c.fill();c.fillStyle='#e4262f';c.textBaseline='middle';c.fillText(tag,x+21,y+29);c.textBaseline='top'}
function thaiDepositDate(){const p=new Intl.DateTimeFormat('th-TH-u-ca-buddhist',{timeZone:'Asia/Bangkok',day:'numeric',month:'short',year:'numeric'}).formatToParts(new Date()),m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.day} ${m.month} ${m.year}`.replace(/\s+/g,' ').trim()}
function analyzeRegion(c,b){try{const x=Math.max(0,Math.floor(b.x)),y=Math.max(0,Math.floor(b.y)),w=Math.max(1,Math.min(W-x,Math.floor(b.w))),h=Math.max(1,Math.min(H-y,Math.floor(b.h))),data=c.getImageData(x,y,w,h).data;let sum=0,sum2=0,n=0;const step=Math.max(4,Math.floor(data.length/3000/4)*4);for(let i=0;i<data.length;i+=step){const lum=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];sum+=lum;sum2+=lum*lum;n++}const avg=sum/Math.max(1,n),variance=sum2/Math.max(1,n)-avg*avg,std=Math.sqrt(Math.max(0,variance));return{avg,std,color:avg>150?'#111111':'#ffffff',needsAssist:std>48||(avg>105&&avg<175)}}catch{return{avg:50,std:0,color:'#fff',needsAssist:false}}}
function drawAssistPanel(c,b,color){c.save();c.fillStyle=color==='#ffffff'?'rgba(0,0,0,.42)':'rgba(255,255,255,.72)';roundedRectOn(c,b.x-18,b.y-14,b.w+36,b.h+28,22);c.fill();c.restore()}
function drawTextLines(c,fit,b,style,weight,lineHeight,maxLines){c.save();c.fillStyle=style.color;c.font=`${weight} ${fit.size}px Tahoma, "Segoe UI", sans-serif`;c.textBaseline='top';applyShadow(c,style);let y=b.y;fit.lines.slice(0,maxLines).forEach(l=>{c.fillText(l,b.x,y);y+=fit.size*lineHeight});c.restore()}
function normalizeInstagram(v){let s=String(v||'').trim();if(!s)return'';try{if(/^https?:\/\//i.test(s)){const u=new URL(s);if(/instagram\.com$/i.test(u.hostname.replace(/^www\./,'')))s=u.pathname.split('/').filter(Boolean)[0]||''}}catch{}s=s.replace(/^@+/,'').replace(/\s+/g,'').replace(/[^A-Za-z0-9._]/g,'').slice(0,30);return s?`@${s}`:''}
function drawInstagram(c,b,text,style){if(!text)return;c.save();const x=b.x,y=b.y;c.strokeStyle=style.color;c.lineWidth=4;applyShadow(c,style);roundedRectOn(c,x,y,34,34,9);c.stroke();c.beginPath();c.arc(x+17,y+17,7,0,Math.PI*2);c.stroke();c.fillStyle=style.color;c.beginPath();c.arc(x+26,y+8,2.6,0,Math.PI*2);c.fill();c.font='700 27px Tahoma, "Segoe UI", sans-serif';c.textBaseline='middle';c.fillText(text,x+47,y+17);c.restore()}

function render(){
  ctx.clearRect(0,0,W,H);drawThemeOn(ctx);const z=zones();const photo=photoImages[0]||null;
  if(photo){ctx.save();roundedRectOn(ctx,z.photo.x,z.photo.y,z.photo.w,z.photo.h,34);ctx.clip();drawCoverOn(ctx,photo,z.photo.x,z.photo.y,z.photo.w,z.photo.h);ctx.restore()}
  drawBadge(ctx);
  const hs=resolveTextStyle(ctx,z.headline,'headline'),bs=resolveTextStyle(ctx,z.body,'body'),ds=resolveTextStyle(ctx,z.date,'date'),is=resolveTextStyle(ctx,z.instagram,'instagram');
  const hfit=fitText(ctx,$('#headline').value,z.headline,{maxSize:82,minSize:42,weight:900,lineHeight:1.12,maxLines:4});
  const bfit=fitText(ctx,$('#bodyText').value,z.body,{maxSize:40,minSize:25,weight:500,lineHeight:1.5,maxLines:8});
  textOverflow=!hfit.fits||!bfit.fits;
  $('#textWarning').classList.toggle('hidden',!textOverflow);$('#submitBtn').disabled=textOverflow;
  if(hs.needsAssist&&$('#headline').value.trim())drawAssistPanel(ctx,z.headline,hs.color);if(bs.needsAssist&&$('#bodyText').value.trim())drawAssistPanel(ctx,z.body,bs.color);
  drawTextLines(ctx,hfit,z.headline,hs,900,1.12,4);drawTextLines(ctx,bfit,z.body,bs,500,1.5,8);
  ctx.save();ctx.fillStyle=ds.color;ctx.font='700 29px Tahoma, "Segoe UI", sans-serif';ctx.textBaseline='top';applyShadow(ctx,ds);ctx.fillText('วันที่ฝาก '+thaiDepositDate(),z.date.x,z.date.y);ctx.restore();
  drawInstagram(ctx,z.instagram,normalizeInstagram($('#instagram').value),is);renderGallery();
}
function gridRects(n){const x=58,y=165,w=964,h=1110,g=18;if(n===1)return[{x,y,w,h}];if(n===2)return[{x,y,w,h:(h-g)/2},{x,y:y+(h+g)/2,w,h:(h-g)/2}];if(n===3){const top=(h-g)/2;return[{x,y,w,h:top},{x,y:y+top+g,w:(w-g)/2,h:top},{x:x+(w+g)/2,y:y+top+g,w:(w-g)/2,h:top}]}if(n===4){const cw=(w-g)/2,ch=(h-g)/2;return[0,1,2,3].map(i=>({x:x+(i%2)*(cw+g),y:y+Math.floor(i/2)*(ch+g),w:cw,h:ch}))}if(n<=6){const cw=(w-g)/2,ch=(h-g*2)/3;return Array.from({length:n},(_,i)=>({x:x+(i%2)*(cw+g),y:y+Math.floor(i/2)*(ch+g),w:cw,h:ch}))}const cw=(w-g*2)/3,ch=(h-g*2)/3;return Array.from({length:n},(_,i)=>({x:x+(i%3)*(cw+g),y:y+Math.floor(i/3)*(ch+g),w:cw,h:ch}))}
function renderGallery(){const extra=photoImages.slice(1,10),wrap=$('#galleryPreviewWrap');if(!extra.length){wrap.classList.add('hidden');return}wrap.classList.remove('hidden');gctx.clearRect(0,0,W,H);drawThemeOn(gctx);gctx.fillStyle='rgba(0,0,0,.30)';gctx.fillRect(0,0,W,H);drawBadge(gctx,58,70);const rects=gridRects(extra.length);extra.forEach((img,i)=>{const r=rects[i];gctx.save();roundedRectOn(gctx,r.x,r.y,r.w,r.h,28);gctx.clip();drawCoverOn(gctx,img,r.x,r.y,r.w,r.h);gctx.restore();gctx.strokeStyle='rgba(255,255,255,.7)';gctx.lineWidth=4;roundedRectOn(gctx,r.x,r.y,r.w,r.h,28);gctx.stroke()})}
async function loadTheme(){try{const r=await fetch('https://fakbok-api.onrender.com/public-config',{cache:'no-store'}),data=await r.json();activeTheme=data.active||{name:'Standard',zones:cloneZones(DEFAULT_ZONES),textStyles:cloneTextStyles(DEFAULT_TEXT_STYLES)};$('#activeThemeName').textContent=activeTheme.name||'Standard';bgImage=null;const bust=u=>u+(u.includes('?')?'&':'?')+'v='+Date.now();if(data.backgroundUrl){try{bgImage=await loadImage(bust(data.backgroundUrl))}catch{if(data.fallbackBackgroundUrl){bgImage=await loadImage(bust(data.fallbackBackgroundUrl));activeTheme=data.fallback||{name:'Standard',type:'standard',zones:cloneZones(DEFAULT_ZONES),textStyles:cloneTextStyles(DEFAULT_TEXT_STYLES)}}}}render()}catch{$('#activeThemeName').textContent='Standard';bgImage=null;activeTheme={name:'Standard',zones:cloneZones(DEFAULT_ZONES),textStyles:cloneTextStyles(DEFAULT_TEXT_STYLES)};render()}}

['headline','bodyText'].forEach(id=>$('#'+id).addEventListener('input',()=>{const counter=$('#'+id.replace('Text','')+'Count');if(counter)counter.textContent=$('#'+id).value.length;render()}));
$('#instagram').addEventListener('input',render);$('#instagram').addEventListener('blur',()=>{$('#instagram').value=normalizeInstagram($('#instagram').value);render()});
$('#photoUpload').addEventListener('change',async e=>{let files=[...e.target.files];if(files.length>10){files=files.slice(0,10);setStatus($('#submitStatus'),'เลือกได้สูงสุด 10 รูป ระบบใช้ 10 รูปแรกให้แล้ว',false)}photoImages=await Promise.all(files.map(fileToImage));$('#photoCount').textContent=photoImages.length?`เลือกแล้ว ${photoImages.length} รูป · ${photoImages.length===1?'ใช้หน้าเดียว':'รูปแรกหน้า 1 + อีก '+(photoImages.length-1)+' รูปหน้า 2'}`:'เลือกได้ 1–10 รูป · รูปแรกหน้า 1 · รูปที่เหลือจัดลงหน้า 2 อัตโนมัติ';render()});
async function canvasBlob(c){return new Promise(res=>c.toBlob(res,'image/png'))}
$('#submitBtn').addEventListener('click',async()=>{const btn=$('#submitBtn');if(textOverflow){setStatus($('#submitStatus'),'ข้อความยาวเกินพื้นที่กราฟิก กรุณาย่อก่อนส่ง',false);return}if(!$('#headline').value.trim()&&!$('#bodyText').value.trim()){setStatus($('#submitStatus'),'กรอกหัวข้อหรือรายละเอียดก่อน',false);return}btn.disabled=true;btn.textContent='กำลังส่ง...';try{render();const page1=await canvasBlob(canvas),fd=new FormData();fd.append('image',page1,'page-1.png');if(photoImages.length>1)fd.append('image2',await canvasBlob(galleryCanvas),'page-2.png');fd.append('headline',$('#headline').value);fd.append('body',$('#bodyText').value);fd.append('instagram',normalizeInstagram($('#instagram').value));fd.append('themeName',activeTheme.name||'');fd.append('photoCount',String(photoImages.length));fd.append('idempotencyKey',currentIdempotency);const r=await fetch('https://fakbok-api.onrender.com/submissions',{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());const result=await r.json();const lineMsg=result.lineNotified?' · Discord แจ้งแอดมินแล้ว ✓':' · บันทึกงานแล้ว แต่ Discord ยังไม่แจ้ง';setStatus($('#submitStatus'),`ส่งเรียบร้อย ✓ รหัสงาน ${result.jobNo||''}${lineMsg}`,!!result.lineNotified);currentIdempotency=crypto.randomUUID();$('#headline').value='';$('#bodyText').value='';$('#instagram').value='';$('#photoUpload').value='';photoImages=[];$('#headlineCount').textContent='0';$('#bodyCount').textContent='0';$('#photoCount').textContent='เลือกได้ 1–10 รูป · รูปแรกหน้า 1 · รูปที่เหลือจัดลงหน้า 2 อัตโนมัติ';render()}catch(e){setStatus($('#submitStatus'),'ส่งไม่สำเร็จ: '+e.message,false)}finally{btn.disabled=textOverflow;btn.textContent='ส่งให้แอดมิน'}});

function showOnly(view){['userView','adminLoginView','adminView'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==view))}
$('#adminOpen').addEventListener('click',()=>{if(adminAuth){showOnly('adminView');loadAdminConfig();loadQueue()}else showOnly('adminLoginView')});$$('[data-close-admin]').forEach(b=>b.addEventListener('click',()=>showOnly('userView')));
$('#adminLoginBtn').addEventListener('click',async()=>{const user=$('#adminUser').value,pass=$('#adminPass').value;try{const r=await fetch('https://fakbok-api.onrender.com/admin-auth',{headers:{'X-Admin-User':user,'X-Admin-Pass':pass}});if(!r.ok)throw new Error('Username หรือ Password ไม่ถูกต้อง');adminAuth={user,pass};sessionStorage.setItem('piriAdmin',JSON.stringify(adminAuth));showOnly('adminView');setStatus($('#loginStatus'),'');await loadAdminConfig();await loadQueue()}catch(e){setStatus($('#loginStatus'),e.message,false)}});
$('#logoutBtn').addEventListener('click',()=>{adminAuth=null;sessionStorage.removeItem('piriAdmin');showOnly('userView')});

async function loadAdminConfig(){try{const r=await fetch('https://fakbok-api.onrender.com/admin-config',{headers:authHeaders(),cache:'no-store'});if(!r.ok)throw new Error(await r.text());adminConfig=await r.json();$('#standardName').value=adminConfig.standard?.name||'';$('#specialName').value=adminConfig.special?.name||'';$('#specialStart').value=adminConfig.special?.start||'';$('#specialEnd').value=adminConfig.special?.end||'';adminZones.standard=cloneZones(adminConfig.standard?.zones||DEFAULT_ZONES);adminZones.special=cloneZones(adminConfig.special?.zones||DEFAULT_ZONES);adminTextStyles.standard=cloneTextStyles(adminConfig.standard?.textStyles||DEFAULT_TEXT_STYLES);adminTextStyles.special=cloneTextStyles(adminConfig.special?.textStyles||DEFAULT_TEXT_STYLES);adminPreviewImages.standard=null;adminPreviewImages.special=null;syncZoneInputs();await drawAdminPreview();await loadTeam()}catch(e){setStatus($('#themeStatus'),'โหลดการตั้งค่าไม่สำเร็จ',false)}}
async function saveTheme(type){const file=type==='standard'?$('#standardFile').files[0]:$('#specialFile').files[0];if(!file){setStatus($('#themeStatus'),'เลือกไฟล์กราฟิกก่อน เพื่อ Preview ก่อนบันทึก',false);return}const fd=new FormData();fd.append('type',type);fd.append('image',file);fd.append('zones',JSON.stringify(adminZones[type]));fd.append('textStyles',JSON.stringify(adminTextStyles[type]));if(type==='standard')fd.append('name',$('#standardName').value||'Standard 1');else{fd.append('name',$('#specialName').value||'Special');fd.append('start',$('#specialStart').value);fd.append('end',$('#specialEnd').value)}const r=await fetch('https://fakbok-api.onrender.com/admin-config',{method:'POST',headers:authHeaders(),body:fd});if(!r.ok)throw new Error(await r.text());setStatus($('#themeStatus'),type==='special'?'เปิดใช้กิจกรรมพิเศษตามช่วงวันที่เรียบร้อย ✓':'บันทึกกราฟิกมาตรฐานเรียบร้อย ✓');await loadTheme();await loadAdminConfig()}
$('#saveStandardBtn').addEventListener('click',()=>saveTheme('standard').catch(e=>setStatus($('#themeStatus'),e.message,false)));$('#saveSpecialBtn').addEventListener('click',()=>saveTheme('special').catch(e=>setStatus($('#themeStatus'),e.message,false)));
$('#clearSpecialBtn').addEventListener('click',async()=>{try{const r=await fetch('https://fakbok-api.onrender.com/admin-config?action=clear-special',{method:'DELETE',headers:authHeaders()});if(!r.ok)throw new Error(await r.text());setStatus($('#themeStatus'),'ล้างกิจกรรมพิเศษแล้ว ระบบจะใช้ Standard ✓');await loadTheme();await loadAdminConfig()}catch(e){setStatus($('#themeStatus'),e.message,false)}});

function currentZoneTarget(){return $('#zoneTheme').value}function currentZoneElement(){return $('#zoneElement').value}
function isTextElement(k=currentZoneElement()){return ['headline','body','date','instagram'].includes(k)}
function syncStyleInputs(){const box=$('#textStyleControls'),e=currentZoneElement();box.classList.toggle('hidden',!isTextElement(e));if(!isTextElement(e))return;const st=adminTextStyles[currentZoneTarget()]?.[e]||DEFAULT_TEXT_STYLES[e];$('#textColorMode').value=st.colorMode||'auto';$('#textColor').value=st.color||'#111111';$('#textColor').disabled=$('#textColorMode').value!=='custom';$('#shadowEnabled').checked=st.shadowEnabled!==false;$('#shadowColor').value=st.shadowColor||'#000000';$('#shadowBlur').value=Number(st.shadowBlur??8);$('#shadowOffsetY').value=Number(st.shadowOffsetY??2);for(const id of ['shadowColor','shadowBlur','shadowOffsetY'])$('#'+id).disabled=!$('#shadowEnabled').checked}
function updateStyleFromInputs(){const t=currentZoneTarget(),e=currentZoneElement();if(!isTextElement(e))return;adminTextStyles[t][e]={colorMode:$('#textColorMode').value==='custom'?'custom':'auto',color:$('#textColor').value,shadowEnabled:$('#shadowEnabled').checked,shadowColor:$('#shadowColor').value,shadowBlur:+$('#shadowBlur').value||0,shadowOffsetY:+$('#shadowOffsetY').value||0};syncStyleInputs();drawAdminPreview()}
function syncZoneInputs(){const z=adminZones[currentZoneTarget()]?.[currentZoneElement()]||DEFAULT_ZONES[currentZoneElement()];for(const [id,k] of [['zoneX','x'],['zoneY','y'],['zoneW','w'],['zoneH','h']])$('#'+id).value=Math.round(z[k]);syncStyleInputs()}
function updateZoneFromInputs(){const t=currentZoneTarget(),e=currentZoneElement();adminZones[t][e]=clampZone({x:+$('#zoneX').value,y:+$('#zoneY').value,w:+$('#zoneW').value,h:+$('#zoneH').value});drawAdminPreview()}
['zoneX','zoneY','zoneW','zoneH'].forEach(id=>$('#'+id).addEventListener('input',updateZoneFromInputs));['textColorMode','textColor','shadowEnabled','shadowColor','shadowBlur','shadowOffsetY'].forEach(id=>$('#'+id).addEventListener('input',updateStyleFromInputs));$('#textColorMode').addEventListener('change',updateStyleFromInputs);$('#shadowEnabled').addEventListener('change',updateStyleFromInputs);$('#zoneTheme').addEventListener('change',()=>{syncZoneInputs();drawAdminPreview()});$('#zoneElement').addEventListener('change',()=>{syncZoneInputs();drawAdminPreview()});
$('#resetZonesBtn').addEventListener('click',()=>{adminZones[currentZoneTarget()]=cloneZones(DEFAULT_ZONES);adminTextStyles[currentZoneTarget()]=cloneTextStyles(DEFAULT_TEXT_STYLES);syncZoneInputs();drawAdminPreview()});
$('#saveZonesBtn').addEventListener('click',async()=>{const type=currentZoneTarget();try{const r=await fetch('https://fakbok-api.onrender.com/admin-config',{method:'PATCH',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({type,zones:adminZones[type],textStyles:adminTextStyles[type]})});if(!r.ok)throw new Error(await r.text());setStatus($('#themeStatus'),`บันทึก Safe Zone + สีข้อความของ ${type==='standard'?'Standard':'กิจกรรมพิเศษ'} แล้ว ✓`);await loadTheme();await loadAdminConfig()}catch(e){setStatus($('#themeStatus'),e.message,false)}});
async function adminPreviewImage(type){if(adminPreviewImages[type])return adminPreviewImages[type];const key=adminConfig?.[type]?.key;if(key){try{return await loadImage('https://fakbok-api.onrender.com/background?key='+encodeURIComponent(key)+'&v='+Date.now())}catch{}}return null}
async function drawAdminPreview(){const type=currentZoneTarget(),img=await adminPreviewImage(type);actx.clearRect(0,0,W,H);if(img)drawCoverOn(actx,img,0,0,W,H);else drawFallbackOn(actx);drawBadge(actx);const z=adminZones[type]||DEFAULT_ZONES;const styles=adminTextStyles[type]||DEFAULT_TEXT_STYLES;const labels={photo:'รูปหลัก',headline:'หัวข้อ',body:'รายละเอียด',date:'วันที่',instagram:'Instagram'};for(const [k,b0] of Object.entries(z)){const b=clampZone(b0);actx.save();actx.strokeStyle=k===currentZoneElement()?'#ef4444':'rgba(255,255,255,.95)';actx.lineWidth=k===currentZoneElement()?7:4;actx.setLineDash(k===currentZoneElement()?[]:[12,8]);actx.strokeRect(b.x,b.y,b.w,b.h);actx.setLineDash([]);actx.fillStyle='rgba(0,0,0,.72)';actx.fillRect(b.x,b.y,Math.min(170,b.w),34);actx.fillStyle='#fff';actx.shadowColor='transparent';actx.shadowBlur=0;actx.font='700 22px Tahoma';actx.fillText(labels[k],b.x+8,b.y+6);actx.globalAlpha=.95;if(isTextElement(k)){const base={...DEFAULT_TEXT_STYLES[k],...(styles[k]||{})},auto=analyzeRegion(actx,b),st={...base,color:base.colorMode==='custom'?base.color:auto.color};applyShadow(actx,st);actx.fillStyle=st.color}if(k==='headline'){actx.font='900 45px Tahoma';actx.fillText('ตัวอย่างหัวข้อ',b.x+12,b.y+55)}else if(k==='body'){actx.font='600 28px Tahoma';actx.fillText('ตัวอย่างรายละเอียดของโพสต์',b.x+12,b.y+55)}else if(k==='date'){actx.font='700 24px Tahoma';actx.fillText('วันที่ฝาก '+thaiDepositDate(),b.x+8,b.y+8)}else if(k==='instagram'){actx.font='700 24px Tahoma';actx.fillText('◎ @example',b.x+8,b.y+8)}else if(k==='photo'){actx.beginPath();actx.moveTo(b.x,b.y);actx.lineTo(b.x+b.w,b.y+b.h);actx.moveTo(b.x+b.w,b.y);actx.lineTo(b.x,b.y+b.h);actx.stroke()}actx.restore()}}
$('#standardFile').addEventListener('change',async()=>{const f=$('#standardFile').files[0];if(f){adminPreviewImages.standard=await fileToImage(f);$('#zoneTheme').value='standard';syncZoneInputs();drawAdminPreview()}});$('#specialFile').addEventListener('change',async()=>{const f=$('#specialFile').files[0];if(f){adminPreviewImages.special=await fileToImage(f);$('#zoneTheme').value='special';syncZoneInputs();drawAdminPreview()}});

async function fetchSubmissionImage(item,page=1){const r=await fetch('https://fakbok-api.onrender.com/submission-image?id='+encodeURIComponent(item.id)+'&page='+page,{headers:authHeaders()});if(!r.ok)return null;return URL.createObjectURL(await r.blob())}
function escapeHtml(s){return String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function formatThaiDateTime(v){if(!v)return'-';try{return new Date(v).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'medium',timeStyle:'short'})}catch{return v}}
async function downloadAll(item){const r=await fetch('https://fakbok-api.onrender.com/submission-download?id='+encodeURIComponent(item.id),{headers:authHeaders()});if(!r.ok){alert('ดาวน์โหลดทั้งหมดไม่สำเร็จ');return}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`${(item.jobNo||'PIRI').replace('#','')}.zip`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
async function loadQueue(){const box=$('#queueList');box.innerHTML='<div class="empty">กำลังโหลด...</div>';try{const r=await fetch('https://fakbok-api.onrender.com/submissions?status='+currentTab,{headers:authHeaders(),cache:'no-store'});if(!r.ok)throw new Error(await r.text());const items=await r.json();if(!items.length){box.innerHTML='<div class="empty">ไม่มีรายการ</div>';return}box.innerHTML='';for(const item of items){const wrap=document.createElement('div');wrap.className='queue-item';const thumbs=document.createElement('div');thumbs.className='queue-thumbs';const img=document.createElement('img');img.className='queue-thumb';img.alt='preview page 1';img.src=await fetchSubmissionImage(item,1)||'';thumbs.appendChild(img);let page2src=null;if((item.pageCount||1)>1){page2src=await fetchSubmissionImage(item,2);if(page2src){const img2=document.createElement('img');img2.className='queue-thumb';img2.alt='preview page 2';img2.src=page2src;thumbs.appendChild(img2)}}const meta=document.createElement('div');meta.className='queue-meta';const deposited=item.depositDateText||item.footer||formatThaiDateTime(item.createdAt),posted=item.postedAt?formatThaiDateTime(item.postedAt):'ยังไม่ลง';meta.innerHTML=`<div class="queue-code">${escapeHtml(item.jobNo||'#PIRI')}</div><h4>${escapeHtml(item.headline||'(ไม่มีหัวข้อ)')}</h4><p>${escapeHtml(item.body||'')}</p><p><small>วันที่ฝาก ${escapeHtml(deposited)} · วันที่ลง ${escapeHtml(posted)}${item.instagram?' · IG '+escapeHtml(item.instagram):''} · ธีม ${escapeHtml(item.themeName||'-')} · ${item.photoCount||0} รูป · ${item.pageCount||1} หน้า</small></p>`;const acts=document.createElement('div');acts.className='queue-actions';const dl=document.createElement('a');dl.textContent='ดาวน์โหลดหน้า 1';dl.href=img.src;dl.download=`${(item.jobNo||'piri').replace('#','')}-1.png`;acts.appendChild(dl);if(page2src){const dl2=document.createElement('a');dl2.textContent='ดาวน์โหลดหน้า 2';dl2.href=page2src;dl2.download=`${(item.jobNo||'piri').replace('#','')}-2.png`;acts.appendChild(dl2);const all=document.createElement('button');all.textContent='ดาวน์โหลดทั้งหมด';all.className='download-all';all.onclick=()=>downloadAll(item);acts.appendChild(all)}const mark=document.createElement('button');mark.textContent=currentTab==='pending'?'✓ ทำแล้ว':'ย้ายกลับ';mark.className='done-btn';mark.onclick=()=>markStatus(item.id,currentTab==='pending'?'done':'pending');acts.appendChild(mark);meta.appendChild(acts);wrap.append(thumbs,meta);box.appendChild(wrap)}}catch(e){console.error(e);box.innerHTML='<div class="empty">โหลดรายการไม่สำเร็จ</div>'}}
async function markStatus(id,status){const r=await fetch('https://fakbok-api.onrender.com/submissions',{method:'PATCH',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(r.ok)loadQueue()}
$$('.tab').forEach(t=>t.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');currentTab=t.dataset.tab;loadQueue()}));$('#refreshQueueBtn').addEventListener('click',loadQueue);

async function loadTeam(){if(!adminAuth)return;const box=$('#teamList');if(!box)return;box.innerHTML='<div class="empty">กำลังโหลด...</div>';try{const r=await fetch('https://fakbok-api.onrender.com/admin-team',{headers:authHeaders(),cache:'no-store'});if(!r.ok)throw new Error(await r.text());const data=await r.json();box.innerHTML='';if(data.ownerConfigured){const note=document.createElement('div');note.className='owner-note';note.textContent='เจ้าของหลักจาก LINE_ADMIN_USER_ID เปิดใช้งานอยู่ ✓';box.appendChild(note)}if(!data.admins?.length){const e=document.createElement('div');e.className='empty';e.textContent='ยังไม่มีแอดมินที่สมัครผ่าน LINE';box.appendChild(e);return}data.admins.forEach((a,i)=>{const row=document.createElement('div');row.className='team-item';const info=document.createElement('div'),name=document.createElement('div');name.className='team-name';name.textContent=a.displayName||`แอดมิน ${i+1}`;const sub=document.createElement('div');sub.className='team-sub';sub.textContent='รับแจ้งเตือนงานใหม่ผ่าน LINE';info.append(name,sub);const del=document.createElement('button');del.className='team-remove';del.textContent='ลบ';del.onclick=async()=>{if(!confirm('ลบแอดมินคนนี้ออกจากการรับแจ้งเตือน?'))return;const rr=await fetch('https://fakbok-api.onrender.com/admin-team?id='+encodeURIComponent(a.userId),{method:'DELETE',headers:authHeaders()});if(rr.ok)loadTeam()};row.append(info,del);box.appendChild(row)})}catch{box.innerHTML='<div class="empty">โหลดทีมแอดมินไม่สำเร็จ</div>'}}
$('#refreshTeamBtn').addEventListener('click',loadTeam);
try{const saved=JSON.parse(sessionStorage.getItem('piriAdmin')||'null');if(saved?.user&&saved?.pass)adminAuth=saved}catch{}
$('#autoDatePreview').textContent=thaiDepositDate();loadTheme();render();
